site_name: Notes
site_url: https://notes.tomondre.com
theme:
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.tabs.sticky
    - toc.follow
    - navigation.top
  hide:
    - navigation
  name: material

nav:
  - Home: ./
  - HashiCorp Terraform Associate: ./terraform associate
  - AWS Cloud Practicioner: ./aws cloud practicioner
  - AWS Solutions Architect Associate: ./aws solutions architect
  - AWS Developer Associate: ./aws developer associate
